# Generated by Django 5.0.3 on 2024-08-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
